#!/usr/bin/env bash
# One-time setup that lets the isoboot e2e test be run via
#   sudo -n /usr/local/sbin/isoboot-e2e [args...]
# from then on.
#
# Run me once with sudo:
#   sudo bash tests/e2e/install-sudo-helper.sh
#
# To uninstall later:
#   sudo rm /usr/local/sbin/isoboot-e2e /etc/sudoers.d/isoboot-e2e

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "install-sudo-helper.sh must run as root (try sudo)" >&2
    exit 1
fi

REPO=$(cd "$(dirname "$0")/../.." && pwd)
SRC="$REPO/tests/e2e/sudo-helper.sh"
DEST="/usr/local/sbin/isoboot-e2e"
SUDOERS="/etc/sudoers.d/isoboot-e2e"
USER_NAME="${SUDO_USER:-$USER}"

if [[ ! -f "$SRC" ]]; then
    echo "missing helper source: $SRC" >&2
    exit 1
fi

install -m 0755 -o root -g root "$SRC" "$DEST"
echo "installed wrapper: $DEST"

cat > "$SUDOERS" <<EOF
# Generated by isoboot tests/e2e/install-sudo-helper.sh
# Lets $USER_NAME run the isoboot e2e test wrapper without a password prompt.
# This grants effective root for anything reachable from
# /home/$USER_NAME/src/isoboot/tests/e2e/run.sh (and scripts it invokes).
# Remove with: sudo rm $SUDOERS $DEST
$USER_NAME ALL=(root) NOPASSWD: $DEST
# Preserve ISOBOOT_ISO_CACHE so users can point the e2e test at a shared
# ISO cache (e.g. on a NAS) without having to pass --cache-dir each time.
Defaults!$DEST env_keep += "ISOBOOT_ISO_CACHE"
EOF
chmod 0440 "$SUDOERS"

# Validate sudoers syntax before leaving the file in place.
if ! visudo -cf "$SUDOERS" >/dev/null; then
    echo "visudo rejected the generated sudoers file; removing it." >&2
    rm -f "$SUDOERS"
    exit 1
fi

echo "installed sudoers entry: $SUDOERS"
echo
echo "Verify with:"
echo "  sudo -ln -U $USER_NAME | grep isoboot-e2e"
echo
echo "Then the e2e test can be invoked non-interactively:"
echo "  sudo -n $DEST                       # smoke test"
echo "  sudo -n $DEST --download-alpine     # boot a real Alpine ISO"
